
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/kiosk-mode/kiosk-mode.js

lovelace:
  mode: storage
  dashboards:
    media-center:
      mode: yaml
      filename: dashboards/media-center.yaml
      title: Media Center
      icon: mdi:remote-tv
      show_in_sidebar: true
    home-climate:
      mode: yaml
      filename: dashboards/climate.yaml
      title: Climate
      icon: mdi:thermometer
      show_in_sidebar: true
    home-lights:
      mode: yaml
      filename: dashboards/lights.yaml
      title: Lights
      icon: mdi:lightbulb-group
      show_in_sidebar: true

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
